// <auto-generated />
using System;
using Hrms.NewApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hrms.NewApi.Migrations
{
    [DbContext(typeof(HrmsDbContext))]
    [Migration("20260608203545_AddSessionToAttendanceRegularizations")]
    partial class AddSessionToAttendanceRegularizations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hrms.NewApi.Models.ActivityMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("activitycode");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("activityname");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<short>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("statuscode");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updatedby");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedon")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ActivityCode")
                        .IsUnique()
                        .HasDatabaseName("uq_activitymaster_activitycode");

                    b.ToTable("activitymaster", (string)null);
                });

            modelBuilder.Entity("Hrms.NewApi.Models.ActivityModuleMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer")
                        .HasColumnName("activityid");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("moduleid");

                    b.Property<short>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("statuscode");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updatedby");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedon")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_activitymodulemapping_activityid");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_activitymodulemapping_moduleid");

                    b.HasIndex("ModuleId", "ActivityId")
                        .IsUnique()
                        .HasDatabaseName("uq_amm_module_activity");

                    b.ToTable("activitymodulemapping", (string)null);
                });

            modelBuilder.Entity("Hrms.NewApi.Models.ActivityRoleMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer")
                        .HasColumnName("activityid");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    b.Property<short>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("statuscode");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updatedby");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedon")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_activityrolemapping_activityid");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_activityrolemapping_roleid");

                    b.HasIndex("ActivityId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("uq_arm_activity_role");

                    b.ToTable("activityrolemapping", (string)null);
                });

            modelBuilder.Entity("Hrms.NewApi.Models.AttendanceRegularization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("approvalstatus");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer")
                        .HasColumnName("approvedby");

                    b.Property<DateTimeOffset?>("ApprovedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approvedon");

                    b.Property<string>("ApproverRemark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("approverremark");

                    b.Property<int?>("AttendanceLogId")
                        .HasColumnType("integer")
                        .HasColumnName("attendancelogid");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("logdate");

                    b.Property<string>("OriginalAttendanceStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("originalattendancestatus");

                    b.Property<DateTimeOffset?>("OriginalCheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("originalcheckintime");

                    b.Property<DateTimeOffset?>("OriginalCheckOutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("originalcheckouttime");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("RequestedCheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requestedcheckintime");

                    b.Property<DateTimeOffset?>("RequestedCheckOutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requestedcheckouttime");

                    b.Property<string>("RequestedCorrectionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("requestedcorrectiontype");

                    b.Property<string>("Session")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("session");

                    b.Property<short>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("statuscode");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updatedby");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatus")
                        .HasDatabaseName("idx_ar_approvalstatus");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("ix_ar_approvedby");

                    b.HasIndex("AttendanceLogId")
                        .HasDatabaseName("ix_ar_attendancelogid");

                    b.HasIndex("LogDate")
                        .HasDatabaseName("idx_ar_logdate");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_ar_userid");

                    b.HasIndex("UserId", "LogDate")
                        .IsUnique()
                        .HasDatabaseName("uq_ar_user_date_pending")
                        .HasFilter("approvalstatus = 'PENDING' AND statuscode = 1");

                    b.ToTable("attendanceregularizations", null, t =>
                        {
                            t.HasCheckConstraint("chk_ar_approvalstatus", "approvalstatus IN ('PENDING','APPROVED','REJECTED','CANCELLED')");

                            t.HasCheckConstraint("chk_ar_correction_type", "requestedcorrectiontype IN ('FULL_DAY','HALF_DAY','SHORT_DAY','FORGOT_CHECK_IN','FORGOT_CHECK_OUT')");

                            t.HasCheckConstraint("chk_ar_original_status", "originalattendancestatus IN ('ABSENT','HALF_DAY','SHORT_DAY','CHECKED_IN')");

                            t.HasCheckConstraint("chk_ar_requested_times", "requestedcheckintime IS NULL OR requestedcheckouttime IS NULL OR requestedcheckouttime > requestedcheckintime");

                            t.HasCheckConstraint("chk_ar_session", "session IS NULL OR session IN ('FIRST_HALF','SECOND_HALF')");
                        });
                });

            modelBuilder.Entity("Hrms.NewApi.Models.CompanyMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("companycode");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("companyname");

                    b.Property<string>("CompanyPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("companyphone");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<short>("FiscalYearStartDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("fiscalyearstartday");

                    b.Property<short>("FiscalYearStartMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)4)
                        .HasColumnName("fiscalyearstartmonth");

                    b.Property<string>("Pincode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pincode");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.Property<short>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("statuscode");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasDefaultValue("Asia/Kolkata")
                        .HasColumnName("timezone");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updatedby");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedon")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode")
                        .IsUnique()
                        .HasDatabaseName("uq_companymaster_companycode");

                    b.ToTable("companymaster", (string)null);
                });

            modelBuilder.Entity("Hrms.NewApi.Models.CompanyPolicies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckInGracePeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15)
                        .HasColumnName("checkin_graceperiod");

                    b.Property<int>("CheckOutGracePeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15)
                        .HasColumnName("checkout_graceperiod");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("companyid");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("HalfDayThreshold")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasDefaultValue(4.00m)
                        .HasColumnName("halfday_threshold");

                    b.Property<int>("RegularizationWindowDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("regularizationwindowdays");

                    b.Property<TimeOnly>("ShiftEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValue(new TimeOnly(17, 0, 0))
                        .HasColumnName("shiftend");

                    b.Property<TimeOnly>("ShiftStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValue(new TimeOnly(9, 0, 0))
                        .HasColumnName("shiftstart");

                    b.Property<short>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("statuscode");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updatedby");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("WorkDays")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("MON,TUE,WED,THU,FRI")
                        .HasColumnName("workdays");

                    b.Property<decimal>("WorkHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasDefaultValue(8.00m)
                        .HasColumnName("workhours");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_companypolicies_companyid");

                    b.ToTable("companypolicies", null, t =>
                        {
                            t.HasCheckConstraint("chk_cp_shift", "shiftend > shiftstart");
                        });
                });

            modelBuilder.Entity("Hrms.NewApi.Models.HolidayList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("companyid");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("HolidayDate")
                        .HasColumnType("date")
                        .HasColumnName("holidaydate");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("holidayname");

                    b.Property<short>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("statuscode");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updatedby");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedon")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_holidaylist_companyid");

                    b.HasIndex("CompanyId", "HolidayDate")
                        .IsUnique()
                        .HasDatabaseName("uq_hl_company_date");

                    b.ToTable("holidaylist", (string)null);
                });

            modelBuilder.Entity("Hrms.NewApi.Models.LeaveApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("approvalstatus");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer")
                        .HasColumnName("approvedby");

                    b.Property<DateTimeOffset?>("ApprovedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approvedon");

                    b.Property<string>("ApproverRemark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("approverremark");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("fromdate");

                    b.Property<bool>("IsHalfDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ishalfday");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("leavetypeid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Session")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("session");

                    b.Property<short>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("statuscode");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date")
                        .HasColumnName("todate");

                    b.Property<decimal>("TotalDays")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("totaldays");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updatedby");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatus")
                        .HasDatabaseName("idx_la_status");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("ix_leaveapplications_approvedby");

                    b.HasIndex("FromDate")
                        .HasDatabaseName("idx_la_fromdate");

                    b.HasIndex("LeaveTypeId")
                        .HasDatabaseName("ix_leaveapplications_leavetypeid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_la_userid");

                    b.ToTable("leaveapplications", null, t =>
                        {
                            t.HasCheckConstraint("chk_la_approvalstatus", "approvalstatus IN ('PENDING','APPROVED','REJECTED','CANCELLED')");

                            t.HasCheckConstraint("chk_la_dates", "todate >= fromdate");

                            t.HasCheckConstraint("chk_la_session", "session IS NULL OR session IN ('FIRST_HALF','SECOND_HALF')");
                        });
                });

            modelBuilder.Entity("Hrms.NewApi.Models.LeaveTypeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("companyid");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCarryForward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("iscarryforward");

                    b.Property<string>("LeaveTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("leavetypename");

                    b.Property<decimal?>("MaxCarryForward")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("maxcarryforward");

                    b.Property<decimal>("MaxDaysAllowed")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("maxdaysallowed");

                    b.Property<short>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("statuscode");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updatedby");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedon")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_leavetypemaster_companyid");

                    b.HasIndex("CompanyId", "LeaveTypeName")
                        .IsUnique()
                        .HasDatabaseName("uq_ltm_company_name");

                    b.ToTable("leavetypemaster", (string)null);
                });

            modelBuilder.Entity("Hrms.NewApi.Models.ModuleMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("iconurl");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modulename");

                    b.Property<int?>("ParentModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("parentmoduleid");

                    b.Property<short>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("statuscode");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updatedby");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedon")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ParentModuleId")
                        .HasDatabaseName("ix_modulemaster_parentmoduleid");

                    b.ToTable("modulemaster", null, t =>
                        {
                            t.HasCheckConstraint("chk_modulemaster_parent_not_self", "parentmoduleid IS NULL OR parentmoduleid <> id");
                        });
                });

            modelBuilder.Entity("Hrms.NewApi.Models.RoleMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("companyid");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rolename");

                    b.Property<short>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("statuscode");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updatedby");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedon")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_rolemaster_companyid");

                    b.HasIndex("CompanyId", "RoleName")
                        .IsUnique()
                        .HasDatabaseName("uq_rolemaster_company_rolename");

                    b.ToTable("rolemaster", (string)null);
                });

            modelBuilder.Entity("Hrms.NewApi.Models.UserAttendanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("attendancestatus");

                    b.Property<DateTimeOffset?>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checkintime");

                    b.Property<DateTimeOffset?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checkouttime");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsEarlyLeave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isearlyleave");

                    b.Property<bool>("IsLate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("islate");

                    b.Property<bool>("IsRegularized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isregularized");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("logdate");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("remarks");

                    b.Property<short>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("statuscode");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updatedby");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<int>("WorkedMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("workedminutes");

                    b.HasKey("Id");

                    b.HasIndex("LogDate")
                        .HasDatabaseName("idx_ual_logdate");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_ual_userid");

                    b.HasIndex("UserId", "LogDate")
                        .IsUnique()
                        .HasDatabaseName("uq_ual_user_date");

                    b.ToTable("userattendancelogs", (string)null);
                });

            modelBuilder.Entity("Hrms.NewApi.Models.UserLeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvailableBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("availablebalance");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("CreditedDays")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("crediteddays");

                    b.Property<short>("CycleYear")
                        .HasColumnType("smallint")
                        .HasColumnName("cycleyear");

                    b.Property<decimal>("FiscalYearCarryForwardIn")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("fiscalyearcarryforwardin");

                    b.Property<string>("LastProcessedMonth")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("lastprocessedmonth");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("leavetypeid");

                    b.Property<decimal>("MonthlyAllocation")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("monthlyallocation");

                    b.Property<decimal>("MonthlyCarryForward")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("monthlycarryforward");

                    b.Property<decimal>("MonthlyPending")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("monthlypending");

                    b.Property<decimal>("MonthlyUsed")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("monthlyused");

                    b.Property<decimal>("OpeningBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("openingbalance");

                    b.Property<short>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("statuscode");

                    b.Property<decimal>("TakenDays")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("takendays");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updatedby");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId")
                        .HasDatabaseName("ix_userleavebalances_leavetypeid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_userleavebalances_userid");

                    b.HasIndex("UserId", "LeaveTypeId", "CycleYear")
                        .IsUnique()
                        .HasDatabaseName("uq_ulb_user_type_year");

                    b.ToTable("userleavebalances", (string)null);
                });

            modelBuilder.Entity("Hrms.NewApi.Models.UserMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("companyid");

                    b.Property<DateOnly?>("ConfirmationDate")
                        .HasColumnType("date")
                        .HasColumnName("confirmationdate");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("emailid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("fullname");

                    b.Property<DateOnly>("JoiningDate")
                        .HasColumnType("date")
                        .HasColumnName("joiningdate");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer")
                        .HasColumnName("managerid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<int>("ProbationMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("probationmonths");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    b.Property<short>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("statuscode");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updatedby");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedon")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("idx_usermaster_companyid");

                    b.HasIndex("EmailId")
                        .IsUnique()
                        .HasDatabaseName("idx_usermaster_emailid");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("ix_usermaster_managerid");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_usermaster_roleid");

                    b.ToTable("usermaster", (string)null);
                });

            modelBuilder.Entity("Hrms.NewApi.Models.ActivityModuleMapping", b =>
                {
                    b.HasOne("Hrms.NewApi.Models.ActivityMaster", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_amm_activity");

                    b.HasOne("Hrms.NewApi.Models.ModuleMaster", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_amm_module");
                });

            modelBuilder.Entity("Hrms.NewApi.Models.ActivityRoleMapping", b =>
                {
                    b.HasOne("Hrms.NewApi.Models.ActivityMaster", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_arm_activity");

                    b.HasOne("Hrms.NewApi.Models.RoleMaster", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_arm_role");
                });

            modelBuilder.Entity("Hrms.NewApi.Models.AttendanceRegularization", b =>
                {
                    b.HasOne("Hrms.NewApi.Models.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_ar_approver");

                    b.HasOne("Hrms.NewApi.Models.UserAttendanceLog", null)
                        .WithMany()
                        .HasForeignKey("AttendanceLogId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_ar_attendance_log");

                    b.HasOne("Hrms.NewApi.Models.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_ar_user");
                });

            modelBuilder.Entity("Hrms.NewApi.Models.CompanyPolicies", b =>
                {
                    b.HasOne("Hrms.NewApi.Models.CompanyMaster", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_cp_company");
                });

            modelBuilder.Entity("Hrms.NewApi.Models.HolidayList", b =>
                {
                    b.HasOne("Hrms.NewApi.Models.CompanyMaster", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_hl_company");
                });

            modelBuilder.Entity("Hrms.NewApi.Models.LeaveApplication", b =>
                {
                    b.HasOne("Hrms.NewApi.Models.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_la_approver");

                    b.HasOne("Hrms.NewApi.Models.LeaveTypeMaster", null)
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_la_leavetype");

                    b.HasOne("Hrms.NewApi.Models.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_la_user");
                });

            modelBuilder.Entity("Hrms.NewApi.Models.LeaveTypeMaster", b =>
                {
                    b.HasOne("Hrms.NewApi.Models.CompanyMaster", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_ltm_company");
                });

            modelBuilder.Entity("Hrms.NewApi.Models.ModuleMaster", b =>
                {
                    b.HasOne("Hrms.NewApi.Models.ModuleMaster", "ParentModule")
                        .WithMany("SubModules")
                        .HasForeignKey("ParentModuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_modulemaster_parent");

                    b.Navigation("ParentModule");
                });

            modelBuilder.Entity("Hrms.NewApi.Models.UserAttendanceLog", b =>
                {
                    b.HasOne("Hrms.NewApi.Models.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_ual_user");
                });

            modelBuilder.Entity("Hrms.NewApi.Models.UserLeaveBalance", b =>
                {
                    b.HasOne("Hrms.NewApi.Models.LeaveTypeMaster", null)
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_ulb_leavetype");

                    b.HasOne("Hrms.NewApi.Models.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_ulb_user");
                });

            modelBuilder.Entity("Hrms.NewApi.Models.UserMaster", b =>
                {
                    b.HasOne("Hrms.NewApi.Models.CompanyMaster", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_user_company");

                    b.HasOne("Hrms.NewApi.Models.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_user_manager");

                    b.HasOne("Hrms.NewApi.Models.RoleMaster", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_user_role");
                });

            modelBuilder.Entity("Hrms.NewApi.Models.ModuleMaster", b =>
                {
                    b.Navigation("SubModules");
                });
#pragma warning restore 612, 618
        }
    }
}
